---
title: "R Notebook"
output: html_notebook
---

```{r}
library(DirichletReg)
library(invgamma)
library(ggplot2)
```

```{r}
p <- 0.65 #Mixture weight

# Component parameters
sigma_1 <- 2
sigma_2 <- 1
mu_1 <- -8 
mu_2 <- -0.5

Theta1 = list("mu"=mu_1, "sigma"= sigma_1)
Theta2 = list("mu"=mu_2, "sigma"= sigma_2)

# Number of samples from the mixture distribution
N <- 3000
# Sample N uniforms U
B <- sample(1:2, size = N, replace = TRUE, prob = c(p, 1-p))

# Sampling from the mixture
Mu <- c(mu_1, mu_2)
Std <- c(sigma_1, sigma_2)
Y <- rnorm(N, mean = Mu[B], sd = Std[B])

mu <- p*mu_1+(1-p)*mu_2
sigma <- sqrt(p*((sigma_1^2)+(mu_1^2)) + (1-p)*((sigma_2^2)+ (mu_2^2)) - (mu^2))

```

```{r}
# Plotting the distributions
ggplot() + 
  geom_histogram(aes(Y), bins = 100)+
  ggtitle("Historgram of the mixture distribution Y")
```

#### Priors

```{r}
Tau <- list("tau1"=10 , "tau2"=10)
Alpha <- c(.5,.5,.5)
ksi <- list("shape"=1.5, "rate"=2)

ggplot()+
  stat_function(fun = dbeta, args = c(Tau$tau1, Tau$tau2))+
  ggtitle("Prior distribution for p")
```

#### Likelihood

$$
\ell(\Theta|y,X) = \prod_{i=1}^{n} \frac{p}{\sqrt{2\pi}\sigma_1} \exp \left( -\frac{(y_i-\mu_1)^2}{2\sigma_1^2} \right) + \frac{1-p}{\sqrt{2\pi}\sigma_2} \exp \left( -\frac{(y_i-\mu_2)^2}{2\sigma_2^2} \right).
$$

```{r}
Log_lik_etaPhi_p_sigma <- function (p_val, etaPhi_val, sigma_val, mu_val, dt){
  mu1 <- mu_val - sigma_val * etaPhi_val[3] * (sqrt(1-p_val)/sqrt(p_val))
  mu2 <- mu_val + sigma_val * etaPhi_val[3] * (sqrt(p_val)/sqrt(1-p_val))
  sigma1 <- sigma_val * (etaPhi_val[1] / sqrt(p_val))
  sigma2 <- sigma_val * (etaPhi_val[2] / sqrt(1-p_val))
  res <- sum(log(p_val*dnorm(dt, mu1, sigma1)  + (1-p_val)* dnorm(dt, mu2, sigma2)))
  return(res)
}
```

#### Posterior

```{r}
Log_post_p <- function (p_val, etaPhi_val, sigma_val, mu_val, Tau, dt) {
  return( Log_lik_etaPhi_p_sigma(p_val, etaPhi_val, sigma_val, mu_val, dt) + log(dbeta(p_val, Tau$tau1, Tau$tau2)))
}

Log_post_etaPhi <- function (p_val, etaPhi_val, sigma_val, mu_val, Alpha, dt){
  return( Log_lik_etaPhi_p_sigma(p_val, etaPhi_val, sigma_val, mu_val, dt) + ddirichlet(matrix(etaPhi_val, nrow = 1), Alpha, log = TRUE))
}

Log_post_sigma <- function ( p_val, etaPhi_val, sigma_val, mu_val, ksi, dt){
  return( Log_lik_etaPhi_p_sigma(p_val, etaPhi_val, sigma_val, mu_val, dt) + dinvgamma(sigma_val, ksi$shape, ksi$rate, log = TRUE))
}

mu_updated <- function (p_val, etaPhi_val, mu_val, sigma_val){
  mu1 <- mu_val - sigma_val * etaPhi_val[3] * (sqrt(1 - p_val) / sqrt(p_val))
  mu2 <- mu_val + sigma_val * etaPhi_val[3] * (sqrt(p_val) / sqrt(1 - p_val))

  # Compute expectation
  return(p_val * mu1 + (1-p_val) * mu_2)
}
```

#### Sampling sigma

```{r}
Ap <- c(0.406^2, 0.149^2, 0.812)
```

```{r}
# Nbr iterations
T <- 10000
T_adapt <- 300
# Mixture std sigma
eps_sigma_sqrd <- 20
sigma_sqrd <- numeric(length = T)
sigma_sqrd[1] <- 4
sigma_sqrd_adapt <- numeric(length = T_adapt)

# Component ecpectations mu1/2
mu1_0 <- 1
mu2_0 <- 1
mu1 <- vector(mode = "numeric", length = T)
mu2 <- vector(mode = "numeric", length = T)
mu1[1] <- mu1_0
mu2[1] <- mu2_0

# Component std sigma1/2
sigma1_0 <- 1
sigma2_0 <- 1
sigma1 <- vector(mode = "numeric", length = T)
sigma2 <- vector(mode = "numeric", length = T)
sigma1[1] <- sigma1_0
sigma2[1] <- sigma2_0
ac_sigma_sqrd <- logical(length = T-1)
ac_rate_sigma_sqrd <- numeric(length = T-1)


# Adaptation
ac_rate_lower <- .325
ac_rate_upper <- .375
cur_adapt <- 100
ac_rate_span <- 50
adapt_eps_sigma_sqrd <- FALSE
nb_adapt <- NULL


for (i in 1:(T-1)){
  sigma_sqrd_t <- sigma_sqrd[i]
  sigma_sqrd_prop <- rinvgamma(1, 2+ ((sigma_sqrd_t^2)/eps_sigma_sqrd), sigma_sqrd_t * ( 1 + (sigma_sqrd_t^2)/eps_sigma_sqrd ))
  
  
  log_acceptance <-
    (
      Log_post_sigma(p,sqrt(Ap), sqrt(sigma_sqrd_prop), mu, ksi, Y) + dinvgamma(sigma_sqrd_t, 2+ ((sigma_sqrd_t^2)/eps_sigma_sqrd), sigma_sqrd_t * ( 1 + (sigma_sqrd_t^2)/eps_sigma_sqrd ), log = TRUE)
    ) - (Log_post_sigma(p, sqrt(Ap), sqrt(sigma_sqrd_t), mu, ksi, Y) + dinvgamma(sigma_sqrd_prop,2+ ((sigma_sqrd_prop^2)/eps_sigma_sqrd), sigma_sqrd_prop * ( 1 + (sigma_sqrd_prop^2)/eps_sigma_sqrd ),  log = TRUE))
  acc_sigma_sqrd <- min(1, exp(log_acceptance))
  
  
  # Decision on the next step
  U = runif(1)
  if (s <- (acc_sigma_sqrd > U))
    sigma_sqrd_next <- sigma_sqrd_prop
  else
    sigma_sqrd_next <- sigma_sqrd_t
  
  # Acceptance rate
  if (i==1) ac_sigma_sqrd[i] <- s
  else ac_sigma_sqrd[i] <- ac_sigma_sqrd[i-1]+s
  ac_rate_sigma_sqrd[i] <- ac_sigma_sqrd[i]/i
  
  sigma_sqrt <- sqrt(sigma_sqrd_next)
  # Update 
  sigma1[i+1] <- sigma_sqrt * (Ap[1] / sqrt(p))
  sigma2[i+1] <- sigma_sqrt * (Ap[2] / sqrt(1 - p))
  mu1[i + 1] <- mu - sigma_sqrt * Ap[3] * (sqrt(1 - p) / sqrt(p))
  mu2[i + 1] <- mu + sigma_sqrt * Ap[3] * (sqrt(p) / sqrt(1 - p))
  
  
  if ((i%%cur_adapt==0) && ((median(ac_rate_sigma_sqrd[(i-cur_adapt/2):i])>.4) || (median(ac_rate_sigma_sqrd[(i-cur_adapt/2):i])<.3))) {
    nb_adapt <- c(nb_adapt, i)
    adapt_eps_sigma_sqrd <- TRUE
    ac_rate_window <- numeric(ac_rate_span)
  }

  if (adapt_eps_sigma_sqrd == TRUE){
    sigma_sqrd_adapt[1] <- sigma_sqrd_next
    for (j in 1:T_adapt){
      sigma_sqrd_t <- sigma_sqrd_adapt[j]
      sigma_sqrd_prop <- rinvgamma(1, 2+ ((sigma_sqrd_t^2)/eps_sigma_sqrd), sigma_sqrd_t * ( 1 + (sigma_sqrd_t^2)/eps_sigma_sqrd ))

      # Computing acceptance probability
      log_acceptance <-
        (
          Log_post_sigma(p,sqrt(Ap), sqrt(sigma_sqrd_prop), mu, ksi, Y) + dinvgamma(sigma_sqrd_t, 2+ ((sigma_sqrd_t^2)/eps_sigma_sqrd), sigma_sqrd_t * ( 1 + (sigma_sqrd_t^2)/eps_sigma_sqrd ), log = TRUE)
        ) - (Log_post_sigma(p, sqrt(Ap), sqrt(sigma_sqrd_t), mu, ksi, Y) + dinvgamma(sigma_sqrd_prop,2+ ((sigma_sqrd_prop^2)/eps_sigma_sqrd), sigma_sqrd_prop * ( 1 + (sigma_sqrd_prop^2)/eps_sigma_sqrd ),  log = TRUE))
      acc_sigma_sqrd <- min(1, exp(log_acceptance))

      # Decision on the next step
      U = runif(1)
      if (s <- (acc_sigma_sqrd > U))
        sigma_sqrd_adapt[j+1] <- sigma_sqrd_prop
      else
        sigma_sqrd_adapt[j+1] <- sigma_sqrd_t

      ac_rate_window[j %% ac_rate_span + 1] <- s

      if (j >= ac_rate_span){
        current_ac_rate <- sum(ac_rate_window) / ac_rate_span

        # Adjust the eps_p
        if (current_ac_rate < ac_rate_lower) eps_sigma_sqrd <- eps_sigma_sqrd*0.95
        else if (current_ac_rate > ac_rate_upper) eps_sigma_sqrd <- eps_sigma_sqrd*1.05
      }
    }
    adapt_eps_sigma_sqrd <- FALSE


  }
  sigma_sqrd[i+1] <- sigma_sqrd_next    
}
n_trunc <- 100
sigma_ <- sqrt(sigma_sqrd)
sigma_ <- sigma_[n_trunc:length(sigma_)]
```

```{r}
ggplot() +
  geom_line(aes(y=ac_rate_sigma_sqrd, x=seq(1,length(ac_rate_sigma_sqrd))))+
  geom_hline(yintercept = ac_rate_lower, linetype ="dashed", color  = "blue")+
  geom_hline(yintercept = ac_rate_upper, linetype ="dashed", color  = "blue")+
  geom_vline(xintercept = nb_adapt, color  ="red")+
  geom_rect(aes(xmin = -Inf, xmax = Inf, ymin= ac_rate_lower, ymax=ac_rate_upper), alpha = .1, fill = "blue")+
  ggtitle("Evolution of the acceptance rate of sigma")+
  labs(y="Acceptance rate", x="Iteration number")
```

```{r}
ggplot() +
  geom_histogram(aes(x=sigma_), bins = 1000) +
  geom_vline(xintercept = sigma, color="red", show.legend = TRUE)  +
  geom_vline(xintercept = mean(sigma_), color="blue", show.legend = TRUE) +
  ggtitle(sprintf("Histogramme des echantillons de sigma\nEn rouge la valeur exacte, en bleu l'estimateur de Bayes\nerr=%.6f", abs(mean(sigma_)-sigma)))
```

#### Sampling with adaptation

```{r}
# Nbr iterations
T <- 5000
T_adapt <- 300

# Mixture weights p
eps_p <- 0.4
P <- numeric(length = T)
p_0 <- rbeta(1,.5, .5)
P[1] <- p_0
P_adapt <- numeric(length = T_adapt)

# Mixture std sigma
eps_sigma_sqrd <- .4
sigma_sqrd <- numeric(length = T)
sigma_sqrd[1] <- 10
sigma_sqrd_adapt <- numeric(length = T_adapt)

# Component ecpectations mu1/2
mu1_0 <- 1
mu2_0 <- 1
mu1 <- vector(mode = "numeric", length = T)
mu2 <- vector(mode = "numeric", length = T)
mu1[1] <- mu1_0
mu2[1] <- mu2_0

# Component std sigma1/2
sigma1_0 <- 1
sigma2_0 <- 1
sigma1 <- vector(mode = "numeric", length = T)
sigma2 <- vector(mode = "numeric", length = T)
sigma1[1] <- sigma1_0
sigma2[1] <- sigma2_0

# Initialization etaPhi (contient les carres de eta_1, eta_2 et Phi )
eps_etaPhi_sqrd <- 300
etaPhi_sqrd_0 <- rdirichlet(1, Alpha)
etaPhi_sqrd <- matrix(NA, T, 3)
etaPhi_sqrd[1, ] <- etaPhi_sqrd_0
etaPhi_sqrd_adapt <- matrix(NA, T_adapt, 3)

# Algorithm vitals
ac_p <-  logical(length = T-1)
ac_rate_p <- numeric(length = T-1)

ac_sigma_sqrd <- logical(length = T-1)
ac_rate_sigma_sqrd <- numeric(length = T-1)

ac_etaPhi_sqrd <-  logical(length = T-1)
ac_rate_etaPhi_sqrd <- numeric(length = T-1)

# Adaptation
ac_rate_lower <- .325
ac_rate_upper <- .375
adapt_eps_etaPhi_sqrd <- FALSE
adapt_eps_p <- FALSE
adapt_eps_sigma_sqrd <- FALSE
cur_adapt <- 300
ac_rate_span <- 75
nb_adapt <- NULL

for (i in 1:(T - 1)) {
  
  # Initialize the Gibbs iteration
  p_t <- P[i]
  etaPhi_sqrd_t <- etaPhi_sqrd[i,]
  sigma_sqrd_t <- sigma_sqrd[i]
  
  ##=======================Sample the mixture weight=====================================>
    #Generate a proposal
    p_prop <- rbeta(1, (p_t*eps_p)+1, ((1-p_t)*eps_p)+1)

    # Computing acceptance
    log_acceptance <- 
      (Log_post_p(p_prop, sqrt(etaPhi_sqrd_t), sqrt(sigma_sqrd_t), mu, Tau, Y) + dbeta(p_t, p_prop*eps_p+1, (1-p_prop)*eps_p+1, log = TRUE)) -
      (Log_post_p(p_t, sqrt(etaPhi_sqrd_t), sqrt(sigma_sqrd_t), mu, Tau, Y) + dbeta(p_prop, p_t*eps_p+1, (1-p_t)*eps_p+1, log = TRUE))
    acc_p <- min(1, exp(log_acceptance))
    
    # Decision on the next step 
    U = runif(1)
    if (s <- (acc_p>U)) p_next <- p_prop
    else p_next <- p_t
    # Acceptance rate
    if (i==1) ac_p[i] <- s
    else ac_p[i] <- ac_p[i-1]+s
    ac_rate_p[i] <- ac_p[i]/i
    
    
    if ((i%%cur_adapt==0) && ((median(ac_rate_p[(i-cur_adapt/2):i])>.4) || (median(ac_rate_p[(i-cur_adapt/2):i])<.3))) {
      i_start <- i
      adapt_eps_p <- TRUE
      ac_rate_window <- numeric(ac_rate_span)
    }
    
    if (adapt_eps_p == TRUE){
      P_adapt[1] <- p_next
      for (j in 1:T_adapt){
        p_t <- P_adapt[j]
        p_prop <- rbeta(1, p_t*eps_p+1, (1-p_t)*eps_p+1)
        
        # Computing acceptance probability
        log_acceptance <- 
        (Log_post_p(p_prop, sqrt(etaPhi_sqrd_t), sqrt(sigma_sqrd_t), mu, Tau, Y) + dbeta(p_t, p_prop*eps_p+1, (1-p_prop)*eps_p+1, log = TRUE)) -
        (Log_post_p(p_t, sqrt(etaPhi_sqrd_t), sqrt(sigma_sqrd_t), mu, Tau, Y) + dbeta(p_prop, p_t*eps_p+1, (1-p_t)*eps_p+1, log = TRUE))
        acc_p <- min(1, exp(log_acceptance))
          
        # Decision on the next step
        U = runif(1)
        if (s <- (acc_p>U)) P_adapt[j+1] <- p_prop
        else P_adapt[j+1] <- p_t
        
        ac_rate_window[j %% ac_rate_span + 1] <- s
        
        if (j >= ac_rate_span){
          current_ac_rate <- sum(ac_rate_window) / ac_rate_span
        
          # Adjust the eps_p 
          if (current_ac_rate < ac_rate_lower) eps_p <- eps_p*1.1
          else if (current_ac_rate > ac_rate_upper) eps_p <- eps_p*0.9
        }
      }
      adapt_eps_p <- FALSE
    }    
    
    
    P[i+1] <- p_next
  ##======================Sample the eta1, et2 and phi all squared========================>
    # Generate a proposal
    etaPhi_sqrd_prop <-
    rdirichlet(1,
               c(
                 etaPhi_sqrd_t[1] * eps_etaPhi_sqrd + 1,
                 etaPhi_sqrd_t[2] * eps_etaPhi_sqrd + 1,
                 etaPhi_sqrd_t[3] * eps_etaPhi_sqrd + 1
               ))

    # Computing acceptance probability
    tmp1 <-
      c(
        etaPhi_sqrd_prop[1] * eps_etaPhi_sqrd + 1,
        etaPhi_sqrd_prop[2] * eps_etaPhi_sqrd + 1,
        etaPhi_sqrd_prop[3] * eps_etaPhi_sqrd + 1
      )
    tmp2 <-
      c(etaPhi_sqrd_t[1] * eps_etaPhi_sqrd + 1,
        etaPhi_sqrd_t[2] * eps_etaPhi_sqrd + 1,
        etaPhi_sqrd_t[3] * eps_etaPhi_sqrd + 1)
    log_acceptance <-
      (
        Log_post_etaPhi(p_next, sqrt(etaPhi_sqrd_prop), sqrt(sigma_sqrd_t), mu, Alpha, Y) + ddirichlet(matrix(etaPhi_sqrd_t, nrow = 1), tmp1 , log = TRUE)
      ) - (Log_post_etaPhi(p_next, sqrt(etaPhi_sqrd_t), sqrt(sigma_sqrd_t), mu, Alpha, Y) + ddirichlet(matrix(etaPhi_sqrd_prop, nrow = 1), tmp2, log = TRUE))
    acc_etaPhi_sqrd <- min(1, exp(log_acceptance))
    
    # Decision on the next step
    U = runif(1)
    if (s <- (acc_etaPhi_sqrd > U))
      etaPhi_sqrd_next <- etaPhi_sqrd_prop
    else
      etaPhi_sqrd_next <- etaPhi_sqrd_t
    
    # Acceptance rate
    if (i==1) ac_etaPhi_sqrd[i] <- s
    else ac_etaPhi_sqrd[i] <- ac_etaPhi_sqrd[i-1]+s
    ac_rate_etaPhi_sqrd[i] <- ac_etaPhi_sqrd[i]/i
    
    
    if ((i%%cur_adapt==0) && ((mean(ac_rate_etaPhi_sqrd[(i-cur_adapt/2):i])>.4) || (mean(ac_rate_etaPhi_sqrd[(i-cur_adapt/2):i])<.3))) {
      adapt_eps_etaPhi_sqrd <- TRUE
      nb_adapt <- c(nb_adapt, i)
      ac_rate_window <- numeric(ac_rate_span)
    }
    
    if (adapt_eps_etaPhi_sqrd == TRUE){
      etaPhi_sqrd_adapt[1,] <- etaPhi_sqrd_next
      for (j in 1:(T_adapt-1)){
        etaPhi_sqrd_t <- etaPhi_sqrd_adapt[j,]
        etaPhi_sqrd_prop <-
          rdirichlet(1,
                     c(
                       etaPhi_sqrd_t[1] * eps_etaPhi_sqrd + 1,
                       etaPhi_sqrd_t[2] * eps_etaPhi_sqrd + 1,
                       etaPhi_sqrd_t[3] * eps_etaPhi_sqrd + 1
                       ))
        # Computing acceptance probability
        C1 <-
          c(
            etaPhi_sqrd_prop[1] * eps_etaPhi_sqrd + 1,
            etaPhi_sqrd_prop[2] * eps_etaPhi_sqrd + 1,
            etaPhi_sqrd_prop[3] * eps_etaPhi_sqrd + 1
          )
        C2 <-
          c(etaPhi_sqrd_t[1] * eps_etaPhi_sqrd + 1,
            etaPhi_sqrd_t[2] * eps_etaPhi_sqrd + 1,
            etaPhi_sqrd_t[3] * eps_etaPhi_sqrd + 1)
        log_acceptance <-
          (
            Log_post_etaPhi(p_next, sqrt(etaPhi_sqrd_prop), sqrt(sigma_sqrd_t), mu, Alpha, Y) + ddirichlet(matrix(etaPhi_sqrd_t, nrow = 1), C1 , log = TRUE)
          ) - (Log_post_etaPhi(p_next, sqrt(etaPhi_sqrd_t), sqrt(sigma_sqrd_t), mu, Alpha, Y) + ddirichlet(matrix(etaPhi_sqrd_prop, nrow = 1), C2, log = TRUE))
        acc <- min(1, exp(log_acceptance))
        # Decision on the next step
        U = runif(1)
        if (s <- (acc>U)) etaPhi_sqrd_adapt[j+1,] <- etaPhi_sqrd_prop
        else etaPhi_sqrd_adapt[j+1,] <- etaPhi_sqrd_t
        
        ac_rate_window[j %% ac_rate_span + 1] <- s
        
        if (j >= ac_rate_span){
          current_ac_rate <- sum(ac_rate_window) / ac_rate_span
        
          # Adjust the eps_p 
          if (current_ac_rate < ac_rate_lower) eps_etaPhi_sqrd <- eps_etaPhi_sqrd*1.1
          else if (current_ac_rate > ac_rate_upper) eps_etaPhi_sqrd <- max(0, eps_etaPhi_sqrd*0.9)
          }
      }
      adapt_eps_etaPhi_sqrd <- FALSE
    }
    
    
    etaPhi_sqrd[i+1,] <- etaPhi_sqrd_next
    # Update sigma1/2
    etaPhi <- sqrt(etaPhi_sqrd[i+1,])
    sigma <- sqrt(sigma_sqrd_t)
    sigma1[i+1] <- sigma * (etaPhi[1] / sqrt(p_next))
    sigma2[i+1] <- sigma * (etaPhi[2] / sqrt(1 - p_next))
    mu1[i + 1] <- mu - sigma * etaPhi[3] * (sqrt(1 - p_next) / sqrt(p_next))
    mu2[i + 1] <- mu + sigma * etaPhi[3] * (sqrt(p_next) / sqrt(1 - p_next))
    
    
    ##======================Sample standard deviation========================>
    sigma_sqrd_prop <- rinvgamma(1, 2+ ((sigma_sqrd_t^2)/eps_sigma_sqrd), sigma_sqrd_t * ( 1 + (sigma_sqrd_t^2)/eps_sigma_sqrd ))
    
    
    log_acceptance <-
      (
        Log_post_sigma(p_next,sqrt(etaPhi_sqrd_next), sqrt(sigma_sqrd_prop), mu, ksi, Y) + dinvgamma(sigma_sqrd_t, 2+ ((sigma_sqrd_t^2)/eps_sigma_sqrd), sigma_sqrd_t * ( 1 + (sigma_sqrd_t^2)/eps_sigma_sqrd ), log = TRUE)
      ) - (Log_post_sigma(p_next, sqrt(etaPhi_sqrd_next), sqrt(sigma_sqrd_t), mu, ksi, Y) + dinvgamma(sigma_sqrd_prop,2+ ((sigma_sqrd_prop^2)/eps_sigma_sqrd), sigma_sqrd_prop * ( 1 + (sigma_sqrd_prop^2)/eps_sigma_sqrd ),  log = TRUE))
    acc_sigma_sqrd <- min(1, exp(log_acceptance))
    
    
    # Decision on the next step
    U = runif(1)
    if (s <- (acc_sigma_sqrd > U))
      sigma_sqrd_next <- sigma_sqrd_prop
    else
      sigma_sqrd_next <- sigma_sqrd_t
    
    # Acceptance rate
    if (i==1) ac_sigma_sqrd[i] <- s
    else ac_sigma_sqrd[i] <- ac_sigma_sqrd[i-1]+s
    ac_rate_sigma_sqrd[i] <- ac_sigma_sqrd[i]/i
    
    sigma_sqrt <- sqrt(sigma_sqrd_next)
    # Update 
    sigma1[i+1] <- sigma_sqrt * (etaPhi[1] / sqrt(p_next))
    sigma2[i+1] <- sigma_sqrt * (etaPhi[2] / sqrt(1 - p_next))
    mu1[i + 1] <- mu - sigma_sqrt * etaPhi[3] * (sqrt(1 - p_next) / sqrt(p_next))
    mu2[i + 1] <- mu + sigma_sqrt * etaPhi[3] * (sqrt(p_next) / sqrt(1 - p_next))
    
    
    if ((i%%cur_adapt==0) && ((median(ac_rate_sigma_sqrd[(i-cur_adapt/2):i])>.4) || (median(ac_rate_sigma_sqrd[(i-cur_adapt/2):i])<.3))) {
      nb_adapt <- c(nb_adapt, i)
      adapt_eps_sigma_sqrd <- TRUE
      ac_rate_window <- numeric(ac_rate_span)
    }
    
    if (adapt_eps_sigma_sqrd == TRUE){
      sigma_sqrd_adapt[1] <- sigma_sqrd_next
      for (j in 1:T_adapt){
        sigma_sqrd_t <- sigma_sqrd_adapt[j]
        sigma_sqrd_prop <- rinvgamma(1, 2+ ((sigma_sqrd_t^2)/eps_sigma_sqrd), sigma_sqrd_t * ( 1 + (sigma_sqrd_t^2)/eps_sigma_sqrd ))
        
        # Computing acceptance probability
        log_acceptance <-
        (
          Log_post_sigma(p_next,sqrt(etaPhi_sqrd_next), sqrt(sigma_sqrd_prop), mu, ksi, Y) + dinvgamma(sigma_sqrd_t, 2+ ((sigma_sqrd_t^2)/eps_sigma_sqrd), sigma_sqrd_t * ( 1 + (sigma_sqrd_t^2)/eps_sigma_sqrd ), log = TRUE)
        ) - (Log_post_sigma(p_next, sqrt(etaPhi_sqrd_next), sqrt(sigma_sqrd_t), mu, ksi, Y) + dinvgamma(sigma_sqrd_prop,2+ ((sigma_sqrd_prop^2)/eps_sigma_sqrd), sigma_sqrd_prop * ( 1 + (sigma_sqrd_prop^2)/eps_sigma_sqrd ),  log = TRUE))
      acc_sigma_sqrd <- min(1, exp(log_acceptance))
        
        # Decision on the next step
        U = runif(1)
        if (s <- (acc_sigma_sqrd > U))
          sigma_sqrd_adapt[j+1] <- sigma_sqrd_prop
        else
          sigma_sqrd_adapt[j+1] <- sigma_sqrd_t
        
        ac_rate_window[j %% ac_rate_span + 1] <- s
        
        if (j >= ac_rate_span){
          current_ac_rate <- sum(ac_rate_window) / ac_rate_span
          
          # Adjust the eps_p
          if (current_ac_rate < ac_rate_lower) eps_sigma_sqrd <- eps_sigma_sqrd*0.95
          else if (current_ac_rate > ac_rate_upper) eps_sigma_sqrd <- eps_sigma_sqrd*1.05
        }
      }
      adapt_eps_sigma_sqrd <- FALSE
      
      
    }
    sigma <- sqrt(sigma_sqrd_next)
    etaPhi <- sqrt(etaPhi_sqrd_next)
    sigma1[i+1] <- sigma * (etaPhi[1] / sqrt(p_next))
    sigma2[i+1] <- sigma * (etaPhi[2] / sqrt(1 - p_next))
    mu1[i + 1] <- mu - sigma * etaPhi[3] * (sqrt(1 - p_next) / sqrt(p_next))
    mu2[i + 1] <- mu + sigma * etaPhi[3] * (sqrt(p_next) / sqrt(1 - p_next))
    
    
    sigma_sqrd[i+1] <- sigma_sqrd_next       
}

n_trunc <- 100
sigma_ <- sqrt(sigma_sqrd)
P <- P[n_trunc:length(P)]
sigma1 <- sigma1[n_trunc:length(sigma1)]
sigma2 <- sigma2[n_trunc:length(sigma2)]
mu1 <- mu1[n_trunc:length(mu1)]
mu2 <- mu2[n_trunc:length(mu2)]
```

```{r}
ggplot() +
  geom_line(aes(y=ac_rate_etaPhi_sqrd, x=seq(1,length(ac_rate_etaPhi_sqrd))))+
  geom_hline(yintercept = ac_rate_lower, linetype ="dashed", color  = "blue")+
  geom_hline(yintercept = ac_rate_upper, linetype ="dashed", color  = "blue")+
  geom_rect(aes(xmin = -Inf, xmax = Inf, ymin= ac_rate_lower, ymax=ac_rate_upper), alpha = .1, fill = "blue")+
  ggtitle("Evolution of the acceptance rate of etaPhi")+
  labs(y="Acceptance rate", x="Iteration number")

ggplot() +
  geom_line(aes(y=ac_rate_p, x=seq(1,length(ac_rate_p))))+
  geom_hline(yintercept = ac_rate_lower, linetype ="dashed", color  = "blue")+
  geom_hline(yintercept = ac_rate_upper, linetype ="dashed", color  = "blue")+
  geom_rect(aes(xmin = -Inf, xmax = Inf, ymin= ac_rate_lower, ymax=ac_rate_upper), alpha = .1, fill = "blue")+
  ggtitle("Evolution of the acceptance rate of p")+
  labs(y="Acceptance rate", x="Iteration number")

ggplot() +
  geom_line(aes(y=ac_rate_sigma_sqrd, x=seq(1,length(ac_rate_sigma_sqrd))))+
  geom_hline(yintercept = ac_rate_lower, linetype ="dashed", color  = "blue")+
  geom_hline(yintercept = ac_rate_upper, linetype ="dashed", color  = "blue")+
  geom_rect(aes(xmin = -Inf, xmax = Inf, ymin= ac_rate_lower, ymax=ac_rate_upper), alpha = .1, fill = "blue")+
  ggtitle("Evolution of the acceptance rate of sigma")+
  labs(y="Acceptance rate", x="Iteration number")
```

```{r}
ggplot() +
  geom_histogram(aes(x=P), bins = 200) +
  geom_vline(xintercept = p, color="red", show.legend = TRUE)  +
  geom_vline(xintercept = mean(P), color="blue", show.legend = TRUE) +
  ggtitle(sprintf("Histogramme des echantillons de p\nEn rouge la valeur exacte, en bleu l'estimateur de Bayes\nerr=%.6f", abs(mean(P)-p)))
```

```{r}
ggplot() +
  geom_histogram(aes(x=mu1), bins = 100) +
  geom_vline(xintercept = mu_1, color="red", show.legend = TRUE)  +
  geom_vline(xintercept = mean(mu1), color="blue", show.legend = TRUE) +
  ggtitle(sprintf("Histogramme des echantillons de mu1\nEn rouge la valeur exacte, en bleu l'estimateur de Bayes\nerr=%.6f", abs(mean(mu1)-mu_1)))


ggplot() +
  geom_histogram(aes(x=mu2), bins = 100) +
  geom_vline(xintercept = mu_2, color="red", show.legend = TRUE)  +
  geom_vline(xintercept = mean(mu2), color="blue", show.legend = TRUE) +
  ggtitle(sprintf("Histogramme des echantillons de mu2\nEn rouge la valeur exacte, en bleu l'estimateur de Bayes\nerr=%.6f", abs(mean(mu2)-mu_2)))
```

```{r}
sigma_true <- sqrt(p*((sigma_1^2)+(mu_1^2)) + (1-p)*((sigma_2^2)+ (mu_2^2)) - (mu^2))
ggplot() +
  geom_histogram(aes(x=sigma_), bins = 300) +
  geom_vline(xintercept = sigma_true , color="red", show.legend = TRUE)  +
  geom_vline(xintercept = mean(sigma_), color="blue", show.legend = TRUE) +
  ggtitle(sprintf("Histogramme des echantillons de sigma\nEn rouge la valeur exacte, en bleu l'estimateur de Bayes\nerr=%.6f", abs(mean(sigma_)-sigma)))
```
